### ISSUE TITLE
[FR] Quit emergency stop button from interface

### ISSUE THREAD

**Issue by pedrosat3d** [KlipperScreen/KlipperScreen#1014]
Would like to completly remove thar button from any panel, is there anyway to do that?

Thanks!

**Comment by alfrix** [comment]
no, there is no way to this and i will not implement it, that functionality is needed, you may never know when but you will.

**Comment by karlfife** [comment]
I can see a case for removing the on-screen e-stop for those who have taken the time to implement a gigantic red E-Stop button.  I know a guy.
