### ISSUE TITLE
[BUG] screen-rotation vertical did not display

### ISSUE THREAD

**Issue by bigtreetech** [KlipperScreen/KlipperScreen#1035]
**Describe the bug**
https://klipperscreen.readthedocs.io/en/latest/Hardware/#screen-rotation
According to the description here, setting the screen rotation vertical screen does not work.
My screen resolution is 1024 * 600.

`normal` and `inverted`(1024*600) be displayed normally and the direction is consistent with the setting.
but `left` and `right`(600*1024) display no content at all, the screen display is completely black.

**To Reproduce**
1. According to https://klipperscreen.readthedocs.io/en/latest/Hardware/#screen-rotation set your screen to vertical mode.
2. restart KlipperScreen
3. The screen does not display any content

**Expected behavior**
The screen can freely switch between horizontal and vertical screen modes according to the settings.

**Comment by alfrix** [comment]
rotation is handled by the os, this is probably a problem with the display drivers, but at least you need to provide the logs to see if something is up with klipperscreen itself or if its something in X

**Comment by bigtreetech** [comment]
Got it. Thanks.
It seems that it is indeed a OS issue and is being further identified. Once I find the problem, I will synchronize the detailed information here. 

Now close this issue to avoid misleading
