### ISSUE TITLE
The MUVE error

### ISSUE THREAD

**Issue by FastivProService** [KlipperScreen/KlipperScreen#1043]
Good day.
There is a problem. Maybe someone will help.  menu does not work. Thanks

![photo_5282938241303039679_y](https://github.com/KlipperScreen/KlipperScreen/assets/80720668/c665366b-e3e1-4264-b30f-97d9aa18884f)
![photo_5282938241303039681_y](https://github.com/KlipperScreen/KlipperScreen/assets/80720668/b353c98c-320b-4991-938a-04b5da1ac234)

**Comment by alfrix** [comment]
there is not enough information, i want to see the full log file to see if there is more clues in there.
there maybe an issue with reading the klipper configuration, i want to see it too
attach the log and klipper config as zip

**Comment by FastivProService** [comment]
[KlipperScreen.conf_1689358000810.zip](https://github.com/KlipperScreen/KlipperScreen/files/12052857/KlipperScreen.conf_1689358000810.zip)

**Comment by FastivProService** [comment]
[KlipperScreen.log](https://github.com/KlipperScreen/KlipperScreen/files/12052859/KlipperScreen.log)

**Comment by alfrix** [comment]
the only thing that can cause this according to my recent testing, is failure to get max_velocity from the printer, that is why i asked for the **_klipper_** config

**Comment by FastivProService** [comment]
[1689437340991.zip](https://github.com/KlipperScreen/KlipperScreen/files/12062077/1689437340991.zip)
thanks for helping me

**Comment by alfrix** [comment]
as i suspected the issue is 
```max_z_velocity: 1```
min and max cannot be equal, i will make a failsafe for this case

**Comment by FastivProService** [comment]
All right. Changed to max_z_velocity 2 and the error disappeared. Thank you.
