### ISSUE TITLE
Klipperscreen reports as working but no display is being shown

### ISSUE THREAD

**Issue by Rubiniuz** [KlipperScreen/KlipperScreen#1049]
### Discussed in https://github.com/KlipperScreen/KlipperScreen/discussions/1048

<div type='discussions-op-text'>

<sup>Originally posted by **Rubiniuz** July 17, 2023</sup>
I have a Odroid N2+ running armbian [https://www.armbian.com/odroid-n2/](url) because of driver support

I haven't had issues before installing klipperscreen. I got a terminal and resolution and refresh rates where all to spec of my display.
Edit: Now it runs the terminial until you see starting klipperscreen. when klipperscreen starts I get a no signal popup from my screen.
I have a brandless 7 inch portable display [https://www.aliexpress.com/item/1005004163930837.html?spm=a2g0o.order_list.order_list_main.17.69b81802YBH8Yv](url). 
It works perfect on ubuntu and on windows with the basic drivers.

running systemctl status Klipperscreen.service gives me a running checkmark and 0 errors or warnings.
I haven't changed the default configs of the os.

I am really stuck and can't find anything. Any ideas are appreciated.

Log:
[KlipperScreen.log](https://github.com/KlipperScreen/KlipperScreen/files/12104499/KlipperScreen.log)

Edit: added KlipperScreen.log
</div>

**Comment by Rubiniuz** [comment]
@alfrix I added the log file.

**Comment by alfrix** [comment]
according to the logs KS is running correctly, the resolution seems wrong (720x576) which may explain the no-signal popup, lcd may not support the configured mode
KlipperScreen does not change or configure the resolution, that has to be configured by you, and depends of the hw used, the manufacturer of the screen is responsible of documenting it, i've never tried armbian or used an odroid

**Comment by Rubiniuz** [comment]
![Display-info](https://github.com/KlipperScreen/KlipperScreen/assets/8469612/0ded919b-3cb9-4ac2-a43c-92c7deeb04f2)
According to this image there is a "fake" display running which KlipperScreen sees as the main screen. do I need to configure this in klipper screen or on os level?

**Comment by alfrix** [comment]
> According to this image there is a "fake" display running which KlipperScreen sees as the main screen. do I need to configure this in klipper screen or on os level?

klipperscreen is just an application, displays are handled by the system.
since it's the only display configure it as primary, i would start in xorg.conf

**Comment by Rubiniuz** [comment]
So I fixed the screen issue but have a new one. klipper screen reports not finding the simpledrm driver. but the screen works in terminal mode. and also on ubuntu. Do you know what might be the issue? like overlapping drivers or it using a wrong driver. the odroid has a mali-g52 gpu

**Comment by alfrix** [comment]
closing as it's not an issue with KS itself, i can only support issues with the application
if someone is in the position of not able of making it work in a lite distro they should go for a desktop distro
https://klipperscreen.readthedocs.io/en/latest/Troubleshooting/Last_resort/

ks can even be used inside a Desktop environment although that path is not entirely finished and not recommended at the moment
