### ISSUE TITLE
[FR] Beacon3D on Zcalibrate

### ISSUE THREAD

**Issue by stenmic** [KlipperScreen/KlipperScreen#1050]
hi, is it possible to add the BEACON_CALIBRATE command in the Zcalibrate panel. The Beacon3D does not work over Klipperscreen.

**Comment by alfrix** [comment]
beacon_calibrate is not part of the klipper base, since it's an extra it cannot be part of the ui as a standard  that would have to be added as:
1. a macro  in the macros panel
2. as a button in your config

example of button:

```
[menu __main more beacon]
name: BEACON CALIBRATE
icon: bed-mesh
method: printer.gcode.script
params: {"script":"BEACON_CALIBRATE"}
confirm:
    {{ gettext('Run BEACON_CALIBRATE?') }}
```
