### ISSUE TITLE
[BUG] Bed mesh numbers not showing on larger mesh

### ISSUE THREAD

**Issue by mpaw** [KlipperScreen/KlipperScreen#1051]
**Describe the bug**
On a 6x6 mesh the numbers are showing up fine, but on a larger mesh (9x9 in my screenshot) the numbers are missing. I'm pretty sure I have seen the numbers there on a 9x9 before so I think this changed in a recent update.

**To Reproduce**
1. Set your mesh to 9x9 in `printer.cfg`
2. Go to `Bed Mesh`
3. Click `Calibrate`
4. View your mesh

**Expected behavior**
The numbers to be there on a 9x9 mesh

**Screenshots**
![Bed Mesh 6x6](https://github.com/KlipperScreen/KlipperScreen/assets/5834637/a5f8b52f-90a3-4ed8-a7e8-657cb34db590)
![Bed Mesh 9x9](https://github.com/KlipperScreen/KlipperScreen/assets/5834637/7ccef795-c352-4379-afc2-a3d06d167ec2)

**Logfile**
[KlipperScreen (1).log](https://github.com/KlipperScreen/KlipperScreen/files/12116417/KlipperScreen.1.log)

**Comment by alfrix** [comment]
this is by design up to 16 rows or 8 columns, and it hasn't changed recently at all (https://github.com/KlipperScreen/KlipperScreen/commit/250574bc41a5e60b7362bb88bd545f41e5c76c62)
