### ISSUE TITLE
[BUG]Installation of PyGobject dependencies failed

### ISSUE THREAD

**Issue by Liechtenstein1** [KlipperScreen/KlipperScreen#1052]
Hello,

I have tried installing KlipperScreen via KIAUH and manually, both gave me tha same error. 
![WhatsApp Image 2023-07-21 at 13 00 09](https://github.com/KlipperScreen/KlipperScreen/assets/112070918/275943a0-09b9-4c81-a2f8-11976ecbc028)

**Comment by alfrix** [comment]
not a bug of klipperscreen, your connection is not reaching the package server, the server may be momentarily down or maintenance or your connection is down (more likely), try again later, if this is wifi, try wired or get closer to the access point
