### ISSUE TITLE
[FR] Spoolman support

### ISSUE THREAD

**Issue by blondak** [KlipperScreen/KlipperScreen#1060]
I started creating spoolman support at https://github.com/blondak/KlipperScreen

Any suggestions and Ideas welcome

**Comment by Mascherino** [comment]
I'm working on spoolman support as well. Is there a reason why you're creating classes and saving everything as attribute when the moonraker server already provides the data in json format?

**Comment by blondak** [comment]
I'm used to, I like strict types and even in classes one can enrich with getters or setters, so no particulat reason.

**Comment by blondak** [comment]
For example you can create a property (icon) https://github.com/blondak/KlipperScreen/blob/master/panels/spoolman.py#L111 with getter get_icon and later in code use https://github.com/blondak/KlipperScreen/blob/master/panels/spoolman.py#L217

**Comment by Mascherino** [comment]
I did not mean to critizise you in any way. I was just curious as I don't think you need to save all the attributes for every spool. But it also depends on how far you want to take the integration for spoolman. I personally think a simple way to choose the currently active spool from a list would be enough.

**Comment by blondak** [comment]
how it looks right now ;)
![image](https://github.com/KlipperScreen/KlipperScreen/assets/125672/429fb98d-2262-4a42-a6a9-d0736734b84c)

**Comment by blondak** [comment]
Added filtering by material
![image](https://github.com/KlipperScreen/KlipperScreen/assets/125672/0829816f-89f1-4b29-91a5-1d45c899c228)
