### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by san3sann** [KlipperScreen/KlipperScreen#1073]
### What happened?

When using Kiauh, using the KlipperScreen function to display the files from the source website cannot be downloaded. If you manually check the original website and find that there are no required files, it may be http://repo.mobian-project.org Has this website removed the files?

### What did you expect to happen instead?

Can be installed normally

### How to reproduce this bug?

Installing through the Kiauh Assistant

### Additional information:

The upper computer and screen are selected from the Hongmi 2a mobile phone, equipped with the Mobian system

### Log output

```shell
错误:4 http://repo.mobian-project.org unstable/main arm64 libpixman-1-dev arm64 0.40.0-1mobian1
  404  Not Found [IP: 91.121.79.211 80]
错误:5 http://repo.mobian-project.org unstable/main arm64 libglib2.0-dev arm64 2.68.1-2mobian1
  404  Not Found [IP: 91.121.79.211 80]
E: 无法下载 http://repo.mobian-project.org/pool/main/g/glib2.0/libglib2.0-dev-bin_2.68.1-2mobian1_arm64.deb  404  Not Found [IP: 91.121.79.211 80]
E: 无法下载 http://repo.mobian-project.org/pool/main/g/glib2.0/libglib2.0-bin_2.68.1-2mobian1_arm64.deb  404  Not Found [IP: 91.121.79.211 80]
E: 无法下载 http://repo.mobian-project.org/pool/main/g/glib2.0/libglib2.0-0_2.68.1-2mobian1_arm64.deb  404  Not Found [IP: 91.121.79.211 80]
E: 无法下载 http://repo.mobian-project.org/pool/main/p/pixman/libpixman-1-dev_0.40.0-1mobian1_arm64.deb  404  Not Found [IP: 91.121.79.211 80]
E: 无法下载 http://repo.mobian-project.org/pool/main/g/glib2.0/libglib2.0-dev_2.68.1-2mobian1_arm64.deb  404  Not Found [IP: 91.121.79.211 80]
E: 有几个软件包无法下载，要不运行 apt-get update 或者加上 --fix-missing 的选项再试试？
Installation of PyGobject dependencies failed (libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0)
```

**Comment by alfrix** [comment]
This is not an issue with klipperscreen, it's an issue with the repositiories of your distro or your internet connection, change mirrors, try again later or change the distro
