### ISSUE TITLE
Power_Device configuration 

### ISSUE THREAD

**Issue by HerrFlodo** [KlipperScreen/KlipperScreen#1103]
### What happened?

I have the power_device configuration done and it's working. But I'm not able to switch the printer on/off using the power switch in Menü. It's not switching at all. Do I have to configure it anyhow or is it may an bug?

Thank you for the great software 🙂

### What did you expect to happen instead?

Power on printer

### How to reproduce this bug?

Not correct configuration I guess 

### Log output

```shell
Is needed?
```

**Comment by alfrix** [comment]
closing, since no log or relevant info was provided
