### ISSUE TITLE
[FR] Camera available during print

### ISSUE THREAD

**Issue by TheLion** [KlipperScreen/KlipperScreen#1107]
### Requested feature

The (default Moonraker) camera is available and viewable when the printer is not actively printing through the "Settings" menu.
But when the printer is actively printing, the "Camera" option is not available anymore in the "Settings" menu. 

When I add a camera manually in the KlipperScreen config, it is available both when not printing and during printing, but then shows 2 cameras, the Moonraker one and the manually defined one in KlipperScreen. 

Is it possible to make the Moonraker camera and/or "Camera" menu option available during printing?

**Comment by alfrix** [comment]
oops this is a bug, forgot to change the menu entry during printing, thanks for reporting
