### ISSUE TITLE
[FR] Use Weblate to facilitate translation

### ISSUE THREAD

**Issue by Daviteusz** [KlipperScreen/KlipperScreen#1116]
If you would like to translate KlipperScreen, you can do this here!
<a href="https://hosted.weblate.org/engage/klipperscreen/">
<img src="https://hosted.weblate.org/widget/klipperscreen/open-graph.png" alt="Stan tłumaczenia" />
</a>

### Requested feature

I translate KlipperScreen using Weblate because it is a very convenient program for translators and is overall perfect for this project.

When the translation is completed, e.g. every 12 hours, the changes are automatically sent as a Pull Request. The entire operation rests on the shoulders of the weblate bot, translators don't need to know git usage to add new translations or update them. Weblate can also generate MO files.

The official Weblate server can host open-source projects for free.

### Additional information

<img src="https://github.com/KlipperScreen/KlipperScreen/assets/11527277/a0f651ab-e1ff-4250-a3c9-bc90f48a0e6d" width=30%>
<img src="https://github.com/KlipperScreen/KlipperScreen/assets/11527277/46042bf1-9445-42cf-93f7-cb6b5c83415e" width=30%>
<img src="https://github.com/KlipperScreen/KlipperScreen/assets/11527277/33152506-d3b1-4cf7-9b06-707d0cd7c20c" width=30%>
<img src="https://github.com/KlipperScreen/KlipperScreen/assets/11527277/c362b0a2-bd1e-4313-9df2-5ec9e8f7291e" width=30%>
<img src="https://github.com/KlipperScreen/KlipperScreen/assets/11527277/b99ce06e-15d6-484c-8a37-fc1b43d555ed" width=30%>
<img src="https://github.com/KlipperScreen/KlipperScreen/assets/11527277/5a07a77f-3208-4f17-b377-1624f11bd72b" width=30%>

**Comment by alfrix** [comment]
sounds interesting, just created a test and invited you 
or we can use yours if you can add me as co-owner

**Comment by Daviteusz** [comment]
I host my instance on a laptop and it is only available every few days, so it is better to use something that works without interruption. 

One good change can be made for better integration with the repository:
- Webhooks: https://docs.weblate.org/en/latest/admin/continuous.html#github-setup

I accepted your invite and I made some changes:
- I set pull request as the method for pushing out changes. It's also possible to push right out to the branch, but I don't feel that's a good idea.
- I also added `ignore-same` flags for **Input Shaper**, **Pressure Advance**, **Slicer**. In this case, translators will not be informed that the translation has not been changed.
- I also added an add-on that generates MO files after each PO change.

It is also possible to add screenshots to each string so that translators will know exactly what they are translating, but with that there is some work to be done.

It seems to me that this is enough to start with. Also, the names and descriptions of commits or pull requests can be changed, but overall the default is ok.

**Comment by alfrix** [comment]
![imagen](https://github.com/KlipperScreen/KlipperScreen/assets/1247237/20be1e3e-4fd2-4192-9b11-0a581fc92041)

**Comment by Daviteusz** [comment]
@alfrix I am currently forced to manually update the repository on Weblate. Could you add webhook in the repository settings? It's just few click :)

https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-github

**Comment by alfrix** [comment]
it seems that most people prefer this method of translation. Thank you [Daviteusz](https://github.com/Daviteusz)
