### ISSUE TITLE
After installing klipperscreen on the ubuntu desktop version, how can I switch directly and freely between the klipperscreen screen and the system desktop screen?[FR] <title>

### ISSUE THREAD

**Issue by 8373907** [KlipperScreen/KlipperScreen#1122]
### Requested feature

After installing klipperscreen on the ubuntu desktop version, how can I switch directly and freely between the klipperscreen screen and the system desktop screen?

**Comment by alfrix** [comment]
you can change to the desktop with `sudo systemctl set-default graphical.target` and reboot
to boot into klipperscreen: `sudo systemctl set-default multi-user.target` and reboot

if you want to use ks inside a desktop environment, it can be done and a .desktop shortcut is provided, but ks is designed to be a fullscreen touch ui, not a regular desktop application, so many caveats apply like no keyboard navigation or mouse tooltips, etc but more importantly no support is provided for this usecase
