### ISSUE TITLE
[BUG] not all macros visible in KS

### ISSUE THREAD

**Issue by Stooovie** [KlipperScreen/KlipperScreen#1123]
### What happened?

Not all macros from my macros.cfg are available in KS. They are NOT hidden in KS macro settings. For example this UNLOAD_FILAMENT macro is nowhere to be found in KS but normally available in both Fluidd and Mainsail. I need this macro to be visible in KS. How can I enforce it?

![Screenshot 2023-09-22 at 12 29 55](https://github.com/KlipperScreen/KlipperScreen/assets/10572373/f2502f89-5b61-4d0d-8ef5-ac85c46d5a7c)

Log
[KlipperScreen (1).log.zip](https://github.com/KlipperScreen/KlipperScreen/files/12699821/KlipperScreen.1.log.zip)

### What did you expect to happen instead?

For all my macros to be available in KS.

### How to reproduce this bug?

Go to Macros in KS.

### Log output

```shell
[KlipperScreen (1).log.zip](https://github.com/KlipperScreen/KlipperScreen/files/12699821/KlipperScreen.1.log.zip)
```

**Comment by alfrix** [comment]
not a bug
UNLOAD_FILAMENT and LOAD_FILAMENT are used in the extrude panel and for that reason they are removed from the macros
see  #1104 for more info
