### ISSUE TITLE
Please Support for ESP32 Arduino LVGL Screen

### ISSUE THREAD

**Issue by PhilippeGalid** [KlipperScreen/KlipperScreen#1142]
### Requested feature

Hi Please make Support for the ESP32 Arduino LVGL Screen

https://www.aliexpress.us/item/1005004502250619.html?spm=a2g0o.productlist.main.1.65dd14f06O3vr6&algo_pvid=7a87a0c3-0670-4601-8027-a83877b671e6&algo_exp_id=7a87a0c3-0670-4601-8027-a83877b671e6-0&pdp_npi=4%40dis%21USD%218.94%218.94%21%21%2165.00%21%21%40210321ea16962174124036282e67be%2112000029387813500%21sea%21US%21862689264%21&curPageLogUid=5YJ5wfilPJaZ&gatewayAdapt=4itemAdapt

**Comment by alfrix** [comment]
KlipperScreen is a linux aplication, it will never support custom screens, the screen needs to act as a normal monitor, as i said multiple times, if it can show the linux desktop it should work
