### ISSUE TITLE
doc: upgrade instructions

### ISSUE THREAD

**Issue by thijstriemstra** [KlipperScreen/KlipperScreen#1155]
### What happened?

Would be nice to have some upgrade instructions in the documentation.

### What did you expect to happen instead?

Can only find installation instructions.

### How to reproduce this bug?

Try upgrading.

**Comment by thijstriemstra** [comment]
for now I created a bash script with:

```sh
#!/bin/bash

source ${HOME}/.KlipperScreen-env/bin/activate
pip --disable-pip-version-check install -r ~/KlipperScreen/scripts/KlipperScreen-requirements.txt
```

**Comment by alfrix** [comment]
the recommendation is to configure moonraker as exaplained in the docs

https://klipperscreen.readthedocs.io/en/latest/Installation/#moonraker-configuration

after that is configured and moonraker is restarted you can use the system panel

![https://klipperscreen.readthedocs.io/en/latest/Panels/#system](https://klipperscreen.readthedocs.io/en/latest/img/panels/system.png)

**Comment by thijstriemstra** [comment]
I run my KlipperScreen on a different Raspberry Pi that uses API to talk to a separate RPI in my network running Klipper/Moonraker. And in that situation, KlipperScreen isn't configured on the Klipper RPI, thus update function isn't available.

**Comment by alfrix** [comment]
> I run my KlipperScreen on a different Raspberry Pi that uses API to talk to a separate RPI in my network running Klipper/Moonraker. And in that situation, KlipperScreen isn't configured on the Klipper RPI, thus update function isn't available.

makes sense, then your are missing the actual update:
```
cd ~/KlipperScreen
git pull
sudo service KlipperScreen restart
```

you can also use [KIAUH](https://github.com/dw-0/kiauh)

**Comment by alfrix** [comment]
added with 524d049
