### ISSUE TITLE
[FR] wwan interface causing network panel shutdown.

### ISSUE THREAD

**Issue by umeiko** [KlipperScreen/KlipperScreen#1175]
### Requested feature

I’m using xiaomi-redmi2 with linux kernel 6.6.0. which is very popular touchscreen device there. but some wwan interface may causing KS’s network panel shutting down. I fixed it simply changing /KlipperScreen/panels/network.py line 33:
self.wirless_interfaces[0] to self.wirless_interfaces[-1] because the wlan interface is the last in the list that and wwan are in the beginning, which seems not supported. maybe there’s some better way to fix this bug with wwan issues?

**Comment by alfrix** [comment]
at some point a selector should be coded
