### ISSUE TITLE
[FR] enable setting IP to remote moonraker instance

### ISSUE THREAD

**Issue by kobold81** [KlipperScreen/KlipperScreen#1180]
### Requested feature

Klipperscreen assumes that it is installed on a printer or on a system with moonraker installed.

The fallback IP in config.py should be changable using a config file to enable KlipperScreen to connect a moonraker instance on a different system. By doing this, one could use a dedicated display/raspberry to have a multi-printer Klipperscreen Interface

### Is your feature request related to a problem?

no

### Describe alternatives you have considered

manually changing config.py

**Comment by alfrix** [comment]
the fallback ip, is just that a fallback if not configured, you should put the address of the moonraker host to connect as described in the docs

https://klipperscreen.readthedocs.io/en/latest/Configuration/#printer-options
