### ISSUE TITLE
[BUG] Wrong progress percentage on KlipperScreen

### ISSUE THREAD

**Issue by alphatrianguli** [KlipperScreen/KlipperScreen#1183]
### What happened?

While the Mainsail web interface shows the correct progress percentage of the current print job, the KlipperScreen progress percentage is always leaping behind...
[logs-20231126-181030.zip](https://github.com/KlipperScreen/KlipperScreen/files/13467526/logs-20231126-181030.zip)

### What did you expect to happen instead?

Progress percentage should match the one in Mainsail

### How to reproduce this bug?

Start any print

### Additional information:

Ender 3 v2, Raspberry Pi 3b+, Waveshare 4.3 Zoll DSI LCD

### Log output

```shell
logs attached
```

**Comment by alfrix** [comment]
klipperscreen progress is time based, it will not match mainsail, different criteria. not a bug, you can select the time estimate method to whatever you prefer in the settings, it will change the progress too.
