### ISSUE TITLE
[FR] Support more than 5 extruders.

### ISSUE THREAD

**Issue by viesturz** [KlipperScreen/KlipperScreen#1195]
### Requested feature

The extruder menu will only show up to 5 extruders. I'm running 6 and that makes the last one inaccessible via the screen.

**Comment by thijstriemstra** [comment]
> The extruder menu will only show up to 5 extruders.

Can you add a screenshot?

**Comment by viesturz** [comment]
![Screenshot_20240115-092904](https://github.com/KlipperScreen/KlipperScreen/assets/1640947/ae48603a-0715-415b-a601-3b26fbab5330)
Sure.
![PXL_20240115_082808229 MP](https://github.com/KlipperScreen/KlipperScreen/assets/1640947/781e3315-0350-4b59-9225-19a925d3251e)

I tried swiping sideways to get to E5 but that does not work as well.
