### ISSUE TITLE
Use docs site for github project url

### ISSUE THREAD

**Issue by thijstriemstra** [KlipperScreen/KlipperScreen#1197]
### Requested feature

The github project url should not be blank and point to https://klipperscreen.readthedocs.io

![issue](https://github.com/KlipperScreen/KlipperScreen/assets/305679/4f5bb23d-ad90-4f4d-b259-9894f9740653)

### Is your feature request related to a problem?

Doc issue

**Comment by alfrix** [comment]
Good suggestion, Done
