### ISSUE TITLE
[FR] Shutdown both host and printer

### ISSUE THREAD

**Issue by thijstriemstra** [KlipperScreen/KlipperScreen#1207]
### Requested feature

Currently it's only possible to shutdown either the Host or the Printer. I'm running KlipperScreen on a separate RPI, using a remote moonraker/klipper installation.

I can choose to Shutdown the Host but this will still keep my printer (separate RPI) running. 

If I shutdown the Printer, Klipperscreen will immediately try to reconnect to the Printer 4 or 5 times and during this time KlipperScreen "hangs" and I'm unable to navigate to the System menu to shutdown the Host. So basically I have to wait for the Moonraker connection to fail before I can shutdown the Printer, very inconvenient.

I suggest to have a "All" or "Both" option that will shutdown the Printer and immediately shutdown the Host as well.

### Additional information

RPI4: moonraker/klipper
RPI3B+: klipperscreen

**Comment by dstulken** [comment]
This is a good idea, and would also be useful for those of us running on a singular device. 

Right now, with one Pi running the printer and KlipperScreen, it's a bit strange to have two shutdown options (Host & Printer), either of which does the same thing.  If these could be unified into a singular "Shutdown" when only one device is configured, it would be a lot more intuitive.
