### ISSUE TITLE
[FR] Add MCU temp to job status panel 

### ISSUE THREAD

**Issue by vipenm** [KlipperScreen/KlipperScreen#1208]
### Requested feature

I have the MCU temp (Pi's temp) displayed on the home screen by adding the following to Klipper's printer.cfg
```
[temperature_sensor MCU]
sensor_type: temperature_host
```
Could it also be displayed during prints (currently only showing extruder and bed temps) in the Job Status panel?

**Comment by alfrix** [comment]
the titlebar items will also be shown on the job status panel (if there is enough space)
https://klipperscreen.readthedocs.io/en/latest/Configuration/#printer-options
