### ISSUE TITLE
Unable to install (iptables)

### ISSUE THREAD

**Issue by lin-ycv** [KlipperScreen/KlipperScreen#1215]
### What happened?

Trying to install a fresh instance to klipper and klipperscreen on Flsun V400, following these instructions [here](https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad/wiki)
I've done this before, and it installs fine, but this time it's not working when installing klipperscreen
as seen [here](https://github.com/Guilouz/Klipper-Flsun-Speeder-Pad/discussions/151) and [here](https://github.com/Guilouz/KlipperScreen-Flsun-Speeder-Pad/issues/29), multiple people are having the same issue
when installing klipperscreen, it gets stuck on `setting up iptables (1.8.4-3ubuntu2.1)` and soft bricks the speeder pad.

I've tried using the custom build of klipperscreen from @Guilouz , i've also tried installing the official build with `kiauh`, neither can install correctly.

### What did you expect to happen instead?

for the install of klipperscreen to proceed normally

### How to reproduce this bug?

do a clean install of klipper and klipperscreen

### Additional information:

Printer: Flsun V400

### Log output

```shell
There are no logs because the install bricks the speeder pad, unable to get the logs.
```

**Comment by Maggan0** [comment]
Same here. After the Klipper screen update my FLSUN V400 Speeder Pad not loading the Klipper screen, had no WiFi Connection and SSH connection was not possible. So I reinstalled Klipper, but the installation of Klipper screen ends up the same like the update. 
I tried it three times.

**Comment by giuspo** [comment]
Hi,
I'm noting the same problem, but I don't know if it is iptables. Because the second time, I performed the Klipperscreen script, stopped elsewhere, but it seems after "Network -manager".

**Comment by Wrathlord12** [comment]
idem probleme a l'installation bloquer a iptables 
![Capture d'écran 2023-12-26 183049](https://github.com/KlipperScreen/KlipperScreen/assets/104155365/1972cb6d-65f3-4d52-b2a4-7c670587343c)

**Comment by alfrix** [comment]
removing `network-manager` from system-dependencies.json will probably fix this

This is not a bug of KlipperScreen, a bug of KlipperScreen is something related to the application itself, this is just an issue in your OS related to the HW

**Comment by alfrix** [comment]
idk how you are connecting to the device, but if it's via network, then it doesn't "brick the pad", you need local access to re-establish the network

**Comment by Wrathlord12** [comment]
le pad est connecté en wifi via le réseau , l'accès ssh est impossible une fois l'erreur apparu

**Comment by giuspo** [comment]
> le pad est connecté en wifi via le réseau , l'accès ssh est impossible une fois l'erreur apparu

Yes, I have the same issue, Even my router no longer sees the speeder pad.

**Comment by giuspo** [comment]
Update...
I removed "network-manager" from the "OPTIONAL" in the script "KlipperScreen-Flsun-Speeder-Pad/scripts/KlipperScreen-install.sh" and the installation of Klipperscreen is finished:

![Immagine 2023-12-27 113032](https://github.com/KlipperScreen/KlipperScreen/assets/7498375/6a88f0d5-95d4-44d9-8b5d-b57e91846d97)

**Comment by Maggan0** [comment]
I am not an expert. Don't know how to do this. Do you have an instruction for me? ☺️

**Comment by Wrathlord12** [comment]
> Je ne suis pas un expert. Je ne sais pas comment faire ça. Avez-vous une instruction pour moi?☺️

idem je suis preneur de la methode merci

**Comment by giuspo** [comment]
In Linux I use "nano" to edit text file.
So, in console edit
sudo nano KlipperScreen/scripts/KlipperScreen-install.sh and after put your password
![image](https://github.com/KlipperScreen/KlipperScreen/assets/7498375/9039d4c7-4320-4a7f-9fb9-158ffe917c07)

In nano editor find the OPTIONAL row:
![image](https://github.com/KlipperScreen/KlipperScreen/assets/7498375/739854bd-4d45-455f-afbc-1a1224dfcdd1)

and remove "network-manager" (really I copied the entire row and paste without network-manager)

after press "CTRL" and "X" to save:
![image](https://github.com/KlipperScreen/KlipperScreen/assets/7498375/ea8c2de1-9184-4d6a-8b91-77cfdcd8e233)

so, execute the script "KlipperScreen-Flsun-Speeder-Pad/scripts/KlipperScreen-install.sh" (like in the wiki) and so on... :-)

**Comment by giuspo** [comment]
So, I don't know if the "network-manager"" is important 🤷‍♀️

**Comment by lin-ycv** [comment]
> So, I don't know if the "network-manager"" is important 🤷‍♀️
from the git history, `network-manager` was only added 4 days ago (to fix a network issue?)
since I have no issues with the previous installs that didn't have it, it's probably fine

**Comment by alfrix** [comment]
> So, I don't know if the "network-manager"" is important 🤷‍♀️

it's necessary for the network panel, the wpa_cli method will be deprecated in 6 months along with 3.7 and debian-buster support

even if you lose connection while installing, if ks starts after the install, then you should be able to reconnect using the network panel, keep in mind that it will probably take a while to finish install after the connection is lost

**Comment by lin-ycv** [comment]
> > So, I don't know if the "network-manager"" is important 🤷‍♀️
> 
> it's necessary for the network panel, the wpa_cli method will be deprecated in 6 months along with 3.7 and debian-buster support
> 
> even if you lose connection while installing, if ks starts after the install, then you should be able to reconnect using the network panel, keep in mind that it will probably take a while to finish install after the connection is lost

is there a rough estimate of "a while"? on my first and second install I waited for over an hour, it never connected back onto my wifi. That's why I was under the impression it was soft-bricked.

**Comment by alfrix** [comment]
> it never connected back onto my wifi. 

it will not connect automatically, as said you need to reconnect using ks or using a keyboard and local tty (idk if that is possible in this device)

**Comment by giuspo** [comment]
> > So, I don't know if the "network-manager"" is important 🤷‍♀️
> 
> it's necessary for the network panel, the wpa_cli method will be deprecated in 6 months along with 3.7 and debian-buster support
> 
> even if you lose connection while installing, if ks starts after the install, then you should be able to reconnect using the network panel, keep in mind that it will probably take a while to finish install after the connection is lost


I noticed that Klipperscreen is also stuck. So, you can not go into the network panel.
Just try to redo the procedure and you will notice the problem that I am having like the others.

**Comment by giuspo** [comment]
> > it never connected back onto my wifi.
> 
> it will not connect automatically, as said you need to reconnect using ks or using a keyboard and local tty (idk if that is possible in this device)

I tried also with a keyboard, but I could not get a console in order to verify the Network connection. Speeder Pad seems stucked!

**Comment by alfrix** [comment]
> I noticed that Klipperscreen is also stuck. So, you can not go into the network panel. Just try to redo the procedure and you will notice the problem that I am having like the others.

i must remind you that i don't have this device, and the nuances are unknown to me, i only have a couple of Raspberry Pi
if your device has a bug in network-manager, fixing it's outside of the scope of this repo, you can blacklist the package to prevent installs via apt-pinning or apt-mark

**Comment by giuspo** [comment]
> > I noticed that Klipperscreen is also stuck. So, you can not go into the network panel. Just try to redo the procedure and you will notice the problem that I am having like the others.
> 
> i must remind you that i don't have this device, and the nuances are unknown to me, i only have a couple of Raspberry Pi if your device has a bug in network-manager, fixing it's outside of the scope of this repo, you can blacklist the package to prevent installs via apt-pinning or apt-mark

I think I will do as you say,, I blacklist the package.
Thanks for your support.
