### ISSUE TITLE
[FR] Unload/Load pop-up options to select a filament type

### ISSUE THREAD

**Issue by razserv2010** [KlipperScreen/KlipperScreen#1232]
### Requested feature

as in Merlin,
For example, when you click on Unalod, a window will open with options for macros that have been predefined by the user.
I am asking for this because I print PLA,PETG,ASA,TPU..
And my Unload/Load macros is set to a temperature of 240, which is too high for PLA.

**Comment by alfrix** [comment]
This should be handled by the user via macros, i will add how to make macro prompts to the documentation
