### ISSUE TITLE
Pin management. I see a slider instead of a switch.

### ISSUE THREAD

**Issue by gumileeev** [KlipperScreen/KlipperScreen#1237]
### Requested feature

My light switch configuration:

```
[output_pin LED]
pin: !PB2
value: 1
pwm: false
```

On the screen I see a slider from 0 to 100, instead of a switch :(
![1](https://github.com/KlipperScreen/KlipperScreen/assets/39103834/9ceb93d8-39d8-4f46-b2fc-3bc08b74a149)
![0](https://github.com/KlipperScreen/KlipperScreen/assets/39103834/97db2439-12f4-489f-b7f2-6c5a857147ab)
![conf](https://github.com/KlipperScreen/KlipperScreen/assets/39103834/f5b4d28a-bc7b-4977-92dc-cbdf51ee7579)

**Comment by alfrix** [comment]
This appears to be a bug
```
#pwm: False
#   Set if the output pin should be capable of pulse-width-modulation.
#   If this is true, the value fields should be between 0 and 1; if it
#   is false the value fields should be either 0 or 1. The default is
#   False.
```
