### ISSUE TITLE
[FR] Graphic interface on the choose printer screen

### ISSUE THREAD

**Issue by XJRpilot** [KlipperScreen/KlipperScreen#1240]
### Requested feature

the graphical interface on the choose printer screen is very plain and i would love to be able to choose a graphic of my actual printer similar to the creality sonic pad.

### Is your feature request related to a problem?

no, not related to any problem

**Comment by thijstriemstra** [comment]
>  similar to the creality sonic pad.

Can you post a screenshot/photo(s)?

**Comment by XJRpilot** [comment]
![klipper screen choose](https://github.com/KlipperScreen/KlipperScreen/assets/145925264/22f85831-a4c1-4740-95cd-3086d8c109fd)
![sonic pad screen choose](https://github.com/KlipperScreen/KlipperScreen/assets/145925264/e294ff1b-4290-4cdc-bdea-2bd48ae3d38f)

**Comment by thijstriemstra** [comment]
Sounds like a nice idea; I'd imagine you'd have to supply the images yourself

**Comment by XJRpilot** [comment]
yes that would be great using them. i have no idea how to implement this. you will keep me informed?
