### ISSUE TITLE
[FR] Host system Battery Status

### ISSUE THREAD

**Issue by phil2sat** [KlipperScreen/KlipperScreen#1262]
### Requested feature

Since i use a tablet and its battery powered i wanted to have a battery Status in the bar.

i know this Feture was requested ages ago and some users all over the web want such a feature.

i think about something:

make a configurable option like 
BATTERY_STATUS_COMMAND: cat /sys/class/power_supply/battery/capacity
which is send periodicly
BATTERY_STATUS_COMMAND_REFRESH: 30 #seconds to refresh

the Output has to be the status in percent, how the user get there is up to him, like with tee and/or some regex

also it would be possible to simply monitor a file on change so either the user writes a script wich periodically updates the file or such file exists like in my case:
/sys/class/power_supply/battery/capacity, under normal circumstances every battery powered linux device has such a file, the location only differs slightly, like someone has:
/sys/class/power_supply/surface-rt-battery/capacity.

Also possible to just run a gcode_shell_command macro and write the output to a file, but thats more complicated since normally klipper runs on another device than klipperscreen. at least in my case (but not impossible ssh will do just fine)

i hope i will knock on some open doors, in my case i would just programm it myself but im unable to write only a single liner in python. Away from this from what i know it cant be that hard to implement.

thanks in advance
phil2sat

### Is your feature request related to a problem?

no

### Describe alternatives you have considered

checked moonraker for such an option to just display it eg as fan but its not possible

**Comment by ChaosBlades** [comment]
@phil2sat This can be closed.
