### ISSUE TITLE
[BUG]  Folders are not shown in the directory with G-codes.

### ISSUE THREAD

**Issue by user32rtu** [KlipperScreen/KlipperScreen#1282]
### What happened?

The error appeared after updating to version v0.3.8-101.
I turn on the printer and the system boots. I go to the print file selection panel and start printing. After printing is complete, I go back to the print file selection panel, but no folders are displayed. After rebooting the system, the folders appear again.
There is no error on version v0.3.7-0.

### What did you expect to happen instead?

Folders should always be visible in the print file selection panel.

### How to reproduce this bug?

1. When the printer is turned on, start printing.
2. After printing is complete, select another file.
3. Folders are not shown in the selection panel.

### Additional information:

Sapphire Pro. 
![2024-02-21_20-03-53](https://github.com/KlipperScreen/KlipperScreen/assets/48878798/f26ff0e3-bad1-4b79-b1fd-a8557d7be779)

### Log output

```shell
[KlipperScreen.log](https://github.com/KlipperScreen/KlipperScreen/files/14362755/KlipperScreen.log)
```

**Comment by CIS94500** [comment]
hi user32rtu, 

this modification fixed the problem for me

in file :
```
KlipperScreen/panels/print.py
```

move line 358 to 365
```
self.filelist = {'gcodes': {'directories': [], 'files': []}}
```
before move :

```
    def reload_files(self, widget=None):
        self.filelist = {'gcodes': {'directories': [], 'files': []}}
        for dirpan in self.dir_panels:
            for column in range(3):
                self.dir_panels[dirpan].remove_column(column)
        self.load_files()

    def load_files(self):
        flist = sorted(self._screen.files.get_file_list(), key=lambda item: '/' in item)
        for file in flist:
            self.add_file(file)
        self.show_directory()
```		
		
after move :

```
    def reload_files(self, widget=None):
        for dirpan in self.dir_panels:
            for column in range(3):
                self.dir_panels[dirpan].remove_column(column)
        self.load_files()

    def load_files(self):
	self.filelist = {'gcodes': {'directories': [], 'files': []}}
        flist = sorted(self._screen.files.get_file_list(), key=lambda item: '/' in item)
        for file in flist:
            self.add_file(file)
        self.show_directory()
```

**Comment by user32rtu** [comment]
Hello CIS94500. Once the printing is finished, I'll try your method.

**Comment by user32rtu** [comment]
> Hello CIS94500. Once the printing is finished, I'll try your method.

Unfortunately, this didn't help.

**Comment by user32rtu** [comment]
> Hello CIS94500. Once the printing is finished, I'll try your method.

Yes, it worked. Thank you !
