### ISSUE TITLE
[FR] Default to "Printer | Menu" when Printer MCU is disconnected.

### ISSUE THREAD

**Issue by PanamonC** [KlipperScreen/KlipperScreen#1284]
### Requested feature

Possible to add the ability to choose which dialog screen is displayed when printer is powered down?

I have a Creality CR10sPro V1.0 that is connected to Homeseer. It is set up to power down after a print and/or 30 mins of idle time. It auto-restarts Klipper whenever the printer turns on via a received print job or by Homeseer, KlipperScreen, the Mainsail GUI, or manually. The Pi 3b+ and the screen stay powered up at all times. It would be great (and look cleaner IMHO) to be able to turn the printer on starting from the "Printer |  Menu" screen. TBH, I would be even happier if I could choose to display the "Printer | Power" button I have created. 

Pics attached.
![Printer - Menu](https://github.com/KlipperScreen/KlipperScreen/assets/160780296/068a6d07-5d53-4b4d-92a3-42f6c5e013f9)
![Printer -Power](https://github.com/KlipperScreen/KlipperScreen/assets/160780296/81cfb568-001e-40f9-b023-5ff755dcea49)

If this is already possible, any help would be much appreciated.

### Describe alternatives you have considered

Either screen could include the current state of the printer in the title. 

(Suggestion)
       Printer | Menu
Klipper has Shutdown.

**Comment by alfrix** [comment]
closing as this is what #934 is already requested

in your case if you want the power button, there is already a method to add it to the splash screen
![imagen](https://github.com/KlipperScreen/KlipperScreen/assets/1247237/62f42fd8-fc59-4890-adaf-c5f8b82b9e69)
https://klipperscreen.github.io/KlipperScreen/Configuration/#printer-options (power_devices)
