### ISSUE TITLE
Cannot install X-server dependency

### ISSUE THREAD

**Issue by pinzarufilip** [KlipperScreen/KlipperScreen#1290]
### What happened?

tried to install Klipperscreen on fluiddpi

### What did you expect to happen instead?

Install Klipperscreen

### How to reproduce this bug?

instal on fluiddpi Klipperscreen.

### Log output

```shell
Selecting previously unselected package libegl-mesa0:armhf.
dpkg: unrecoverable fatal error, aborting:
 files list file for package 'ocl-icd-libopencl1:armhf' contains empty filename
E: Sub-process /usr/bin/dpkg returned an error code (2)
Installation of X-server dependencies failed (xinit xinput x11-xserver-utils xserver-xorg-input-evdev xserver-xorg-input-libinput)

#=======================================================#
 KlipperScreen installation failed!
#=======================================================#
```

**Comment by alfrix** [comment]
do not use FluiddPI

![imagen](https://github.com/KlipperScreen/KlipperScreen/assets/1247237/5e36d8f9-05f0-46d5-b726-303a3f54ce6a)

**Comment by CybrGost69** [comment]
same thing JUST happened to me while installing KlipperScreen via KIAUH.
