### ISSUE TITLE
[BUG] Bed level (screws_tilt_adjust) displays wrong number of screws + wrong screws coordinates (ignores probe offset)

### ISSUE THREAD

**Issue by magnificu** [KlipperScreen/KlipperScreen#1298]
### What happened?

Even though 4 screws are defined in printer.cfg, only 3 screws are shown in KlipperScreen Bed level menu.
![20240310_222722](https://github.com/KlipperScreen/KlipperScreen/assets/63443841/95517c88-5a42-43c9-8431-765dd6306413)

When touch (click) one of the corners the printer moves to wrong coordinates. This could lead to hardware damage.

### What did you expect to happen instead?

To see 4 screws in the menu and in "screws_tilt_adjust" the probe to be above the screws

### How to reproduce this bug?

latest github commit: a32d1d8e8085724068ac6a43adbba9757228aebb from Mar 10, 2024

1) Set in printer.cfg a probe with an offset and add 4 screws in "screws_tilt_adjust"

[bltouch]
sensor_pin: ^PE4
control_pin: PE5
x_offset: -23
y_offset: 36
z_offset: 0.6
samples: 1

[screws_tilt_adjust]
screw1: 40, 40
screw1_name: FL-screw
screw2: 260, 40
screw2_name: FR-screw
screw3: 260, 260
screw3_name: BR-screw
screw4: 260, 40
screw4_name: BL-screw
horizontal_move_z: 5
speed: 60
screw_thread: CW-M4

2) restart Klipper & KlipperScreen

3) Check in KlipperScreen Bed level -> only 3 screws are visible

4a) Screw adjust button (click) -> Homes and starts probing: FL-screw, FR-screw, BR-screw and again FR-screw (BL-screw is never probed)

or
4b) Press one corner screw -> the probe moves to wrong coordinates and the nozzle crashes into the bed

### Additional information:

[printer.cfg.zip](https://github.com/KlipperScreen/KlipperScreen/files/14551792/printer.cfg.zip)

### Log output

```shell
[KlipperScreen.log.zip](https://github.com/KlipperScreen/KlipperScreen/files/14551850/KlipperScreen.log.zip)
```

**Comment by alfrix** [comment]
there are 4 screws shown, one is shown as front-middle because your 4th screw have incorrect coordinates and the code tries but fails to make sense of where it is

more info on what does what and why in the docs.
https://klipperscreen.readthedocs.io/en/latest/Panels/Screws/
