### ISSUE TITLE
[BUG] Cartographer probe coil temperature isn't displayed

### ISSUE THREAD

**Issue by HakunMatat4** [KlipperScreen/KlipperScreen#1309]
### What happened?

I am trying to add the cartographer probe coil temperature to the main screen.
On klipper it is set as `[cartographer]` so I tried:

`titlebar_items: chamber, MCU, cartographer # Even cartographer_coil for the matter, you will understand why.
`

KlipperScreen sees it but the temperature isn't displayed.
I checked the documentation for any complementar info but I cannot find anything: https://klipperscreen.readthedocs.io/en/latest/Configuration/?h=titl#printer-options

`2024-03-21 10:31:39,520 [printer.py:init_temp_store()] - Temp store: ['temperature_sensor cartographer_coil', 'heater_bed', 'temperature_sensor chamber_temp', 'temperature_sensor mcu_temp', 'extruder']`

![PXL_20240318_090504551~2](https://github.com/KlipperScreen/KlipperScreen/assets/35049512/c0e646c9-48ba-48b0-9321-6433e9d08526)

### What did you expect to happen instead?

I expected the probe coil temperature to show up here.
This is a 7"display

![PXL_20240318_090504551~2](https://github.com/KlipperScreen/KlipperScreen/assets/35049512/a5ecd919-0b80-46e3-a451-ca7666c131fb)

### How to reproduce this bug?

Try to add a temperature sensor other than the stock ones like bed, nozzle, mcu, extruder, Pi and nothing happens.

### Log output

```shell
GitHub isn't showing a pop-up to upload the logs so I will try to upload it after opening the ticket
```

**Comment by HakunMatat4** [comment]
Log uploaded!
Thank you

[KlipperScreen.log.zip](https://github.com/KlipperScreen/KlipperScreen/files/14675879/KlipperScreen.log.zip)

**Comment by alfrix** [comment]
This is not valid as a bug report, klipperscreen docs states that valid options are: 
> temperature_sensors or temperature_fans, or heater_generic

https://klipperscreen.github.io/KlipperScreen/Configuration/#printer-options

your configuration shows:

```
[printer Trident]
titlebar_items = chamber, MCU, cartographer_coil
```
and it doesn't match your devices

> the name must be the same as defined in the klipper config

```
2024-03-21 10:31:39,500 [main_menu.py:add_device()] - Adding device: extruder
2024-03-21 10:31:39,501 [main_menu.py:add_device()] - Adding device: heater_bed
2024-03-21 10:31:39,503 [main_menu.py:add_device()] - Adding device: temperature_sensor chamber_temp
2024-03-21 10:31:39,504 [main_menu.py:add_device()] - Adding device: temperature_sensor mcu_temp
```

you need to write:

```
[printer Trident]
titlebar_items = chamber_temp, mcu_temp
```

if you want cartographer_coil it would need to be defined as temperature_sensor in klipper or else is not supported and it's not a bug but a feature request

**Comment by HakunMatat4** [comment]
>if you want cartographer_coil it would need to be defined as temperature_sensor in klipper or else is not supported and it's not a bug but a feature request

Ahhh I understand it now.
Thank you for the explanation, it makes more sense.
Cheers
