### ISSUE TITLE
[BUG] Klipper Screen not showing after initial boot up

### ISSUE THREAD

**Issue by ikarus-71** [KlipperScreen/KlipperScreen#1311]
### What happened?

I am running Klipper on a laptop (Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-101-generic x86_64)). I connected a BIGTREETECH HDMI5 V1.1 to laptop through HDMI. When Klipper is booting I can see the bootsteps on the screen, so I am sure that screen is working. But when boot sequence finish I only see a blank screen. I already followed steps in the troubleshooting website, none worked.
![klipperscreen](https://github.com/KlipperScreen/KlipperScreen/assets/73074122/373f96ef-a3d8-442e-bb7a-0e029f3e97b5)
[logs-20240321-233142.zip](https://github.com/KlipperScreen/KlipperScreen/files/14706886/logs-20240321-233142.zip)

### What did you expect to happen instead?

Klipper screen showing on BTT HDMI5

### How to reproduce this bug?

Running an external klipperscreen on a laptop

### Log output

```shell
Logs attached
```

**Comment by alfrix** [comment]
from you logs, klipperscreen is working correctly, you need to set the default monitor in xorg or maybe try the provided settings in ks (https://klipperscreen.github.io/KlipperScreen/Configuration/#adding-launch-arguments), but either way it's not a valid klipperscreen bug, it's a system configuration issue
