### ISSUE TITLE
[BUG] Red titlebar after update

### ISSUE THREAD

**Issue by Bimbovadasz** [KlipperScreen/KlipperScreen#1316]
### What happened?

After updating to v0.3.9-64-g1c9d82ad the top titlebar got a red overlay that also shows incorrect values for CPU and RAM utilizations. When I switch between panels the red overlay takes a bit to load so I can see for a moment the original correct titlebar.
Is this a bug or a feature?
If it is a feature, how can I turn it off?

![IMG_8947](https://github.com/KlipperScreen/KlipperScreen/assets/35198213/b839f926-16fd-4088-93b9-84c4af013ce2)

I tried to remove and reinstall klipperscreen, but it did not work.

### What did you expect to happen instead?

I expect the correct titlebar

### How to reproduce this bug?

Update to v0.3.9-64-g1c9d82ad

### Additional information:

[KlipperScreen.log](https://github.com/KlipperScreen/KlipperScreen/files/14781827/KlipperScreen.log)
[KlipperScreen2.log](https://github.com/KlipperScreen/KlipperScreen/files/14781835/KlipperScreen2.log)

### Log output

```shell
Updated to additional info
```

**Comment by alfrix** [comment]
reports are from the moonraker (printer) it seems that the core usage reports are somewhat higher than the reports of htop, i don't have time to look at moonrakers code, but the avg seems to be similar, so i changed to use that in b93fd08b6fa0701971e6eb9e96e74e34154c5701
