### ISSUE TITLE
Power ON button on the home screen

### ISSUE THREAD

**Issue by blonestar** [KlipperScreen/KlipperScreen#1336]
### Requested feature

Power ON button would be nice to have within click on the main/home screen for relay controlled printers.

![image](https://github.com/KlipperScreen/KlipperScreen/assets/5240133/0ec28b8d-6709-480e-a1ec-d5d1558827de)
![20240416_080120](https://github.com/KlipperScreen/KlipperScreen/assets/5240133/7187546a-f335-4410-b314-b561ee355d7b)

### Is your feature request related to a problem?

I find just a bit hard to turn on my printer from the KlipperScreen as I'm using relay to control it.
On the other hand it is quite easy to do that from the Mainsail.
![image](https://github.com/KlipperScreen/KlipperScreen/assets/5240133/dba57c53-1bba-4242-907b-c442809adaf8)

### Describe alternatives you have considered

Need to open Menu > Power to get to the Relay/Power controls

![20240416_080159](https://github.com/KlipperScreen/KlipperScreen/assets/5240133/54f0fe67-6ea1-416f-895e-157936836d1d)

### Additional information

Relays are controlled  through the Moonraker and GPIOs on the Pi (BTT Pi in this case)

![image](https://github.com/KlipperScreen/KlipperScreen/assets/5240133/516a3747-cfb5-4d48-8d37-7aca643ebac2)

**Comment by mjfsch** [comment]
This already exists - however it is sometimes a little tricky to get working 

The main thing to get it working, is the power device and the printer need to have the same name, currently your power device is called "Printer" but your printer is called "Trident"

https://github.com/KlipperScreen/KlipperScreen/issues/1241

**Comment by blonestar** [comment]
Just added this line to the klipperscreen.conf and it's working.
`power_devices: Printer`
Thank you, 
will close the issue

![20240416_122502](https://github.com/KlipperScreen/KlipperScreen/assets/5240133/8c363c98-2830-45a5-82e8-e660ea50c77a)
