### ISSUE TITLE
[BUG] Unable to install KlipperScreen with python3.12

### ISSUE THREAD

**Issue by fqscfqj** [KlipperScreen/KlipperScreen#1345]
### What happened?

When I was installing KlipperScreen using KIAUH, a malfunction occurred. Upon searching, it seems that the issue might be due to the absence of distutils in Python 3.12.

### What did you expect to happen instead?

Installation completed

### How to reproduce this bug?

During the installation process

### Additional information:

I'm using a Redmi Note 4X, running Ubuntu 24.04.

###### Create backup of /home/umeko/printer_data/config ...
[✓ OK] Backup created in:
/home/umeko/kiauh-backups/configs/240426-1920/printer_data

###### Checking for the following dependencies:
● wget 
● curl 
● unzip 
● dfu-util 
[✓ OK] Dependencies already met!

###### Cloning KlipperScreen from https://github.com/jordanruthe/KlipperScreen.git ...
Cloning into '/home/umeko/KlipperScreen'...
remote: Enumerating objects: 14448, done.
remote: Counting objects: 100% (160/160), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 14448 (delta 81), reused 142 (delta 78), pack-reused 14288
Receiving objects: 100% (14448/14448), 13.17 MiB | 7.37 MiB/s, done.
Resolving deltas: 100% (9529/9529), done.

###### Installing KlipperScreen ...
Checking Python version
Python 3.12.3
Install as a service? (This will enable boot to console) [Y/n]n
Not installing the service
The graphical backend will NOT be installed
Update package data
Hit:1 http://ports.ubuntu.com/ubuntu-ports noble InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports noble-updates InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports noble-backports InRelease
Hit:4 http://ports.ubuntu.com/ubuntu-ports noble-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Checking for broken packages...
No broken packages
Installing KlipperScreen dependencies
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-nanum is already the newest version (20200506-1).
fonts-ipafont is already the newest version (00303-21ubuntu1).
libmpv-dev is already the newest version (0.37.0-1ubuntu4).
policykit-1 is already the newest version (124-2ubuntu1).
network-manager is already the newest version (1.46.0-1ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
network-manager
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python3-distutils is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-distutils' has no installation candidate
Installation of Python dependencies failed (python3-virtualenv virtualenv python3-distutils)

#=======================================================#
 KlipperScreen installation failed! 
#=======================================================#

**Comment by alfrix** [comment]
it shouldn't be needed anymore

for context:
it was needed previous to the switch to pygobject, now the gobject library marks that package as needed if necessary, so there is no need for adding it explicitly
