### ISSUE TITLE
[BUG] printers folder displayed in themes list

### ISSUE THREAD

**Issue by Guilouz** [KlipperScreen/KlipperScreen#1362]
### What happened?

Since PR https://github.com/KlipperScreen/KlipperScreen/issues/1240, printers folder for custom icons is also displayed in themes list.

### What did you expect to happen instead?

The printers folder should not appear.

### How to reproduce this bug?

Just go in KlipperScreen panel and select theme in themes list.

### Log output

No log file

**Comment by alfrix** [comment]
fixed with [c9c6eb2](https://github.com/KlipperScreen/KlipperScreen/commit/c9c6eb2258d8c65a8bb5450ac8ca434d28e1c7af) thanks for reporting
