### ISSUE TITLE
[BUG] Language is not saved

### ISSUE THREAD

**Issue by Guilouz** [KlipperScreen/KlipperScreen#1363]
### What happened?

Since PR https://github.com/KlipperScreen/KlipperScreen/commit/f704c56ae8a0a635db7c06e0ae12f55fe73b99ab, when a language is selected, it is correctly applied but after a restart it is the default language (en) which loads.

### What did you expect to happen instead?

The selected language must be saved.

### How to reproduce this bug?

Select a language other than English and restart KlipperScreen, English language is reloaded.

### Log output

[KlipperScreen.log.zip](https://github.com/KlipperScreen/KlipperScreen/files/15265892/KlipperScreen.log.zip)

**Comment by alfrix** [comment]
03a99ded924701c8103e4f0d5b3446ee3dd8580f
