### ISSUE TITLE
[BUG] job_status.py hammering Klipper in search of a thumbnail

### ISSUE THREAD

**Issue by Cyberwizzard** [KlipperScreen/KlipperScreen#1366]
### What happened?

While diagnosing a problem with Klipper where some prints failed due to a "Timer too close" error, I noticed that the system journal is flooded with these:
```
May 13 19:23:36 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:23:36,719 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:23:36 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:23:36,720 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:23:36 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:23:36,721 [job_status.py:show_file_thumbnail()] - no pixbuf
```

These three lines are repeating, every 5 ms (!) while printing.

The gcode is generated by PrusaSlicer 2.7.4, and indeed there is no thumbnail preview. So perhaps there is a problem between Klipper and PrusaSlicer with respect to the generated thumbnail.

However, the logic in job_status.py seems to continuously request the thumbnail pixmap over and over again, causing an increased load on the Klipper host, which in some cases causes print failures.

### What did you expect to happen instead?

KlipperScreen should retry on an interval, like once a second - not 200 times per second.

### How to reproduce this bug?

Make a gcode file with PrusaSlicer 2.7.4 and load it up in Klipper to print. No thumbnail is shown and the system journal (`journalctl -a`) is flooded with these messages.

### Additional information:

I now disabled the re-request of the thumbnail if it at first does not show up. Ideally a retry is done once a second or so, but clearly in a loop like this, it causes issues.

```
diff --git a/panels/job_status.py b/panels/job_status.py
index f46429c..04de042 100644
--- a/panels/job_status.py
+++ b/panels/job_status.py
@@ -808,5 +808,5 @@ class Panel(ScreenPanel):
                 self.labels['filament_total'].set_label(f"{float(self.file_metadata['filament_total']) / 1000:.1f} m")
         else:
             logging.debug("Cannot find file metadata. Listening for updated metadata")
-            self._files.request_metadata(self.filename)
+            # self._files.request_metadata(self.filename)
         self.show_file_thumbnail()
```

### Log output

-- Journal begins at Mon 2024-05-13 16:30:46 BST, ends at Mon 2024-05-13 19:41:20 BST. --
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:24:59,992 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,002 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,003 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,003 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,009 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,010 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,011 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,016 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,017 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,018 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,023 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,025 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,025 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,030 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,032 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,032 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,038 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,039 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,040 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,046 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,047 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,047 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,054 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,055 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,056 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,061 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,062 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,063 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,068 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,070 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,070 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,075 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,076 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,077 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,082 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,083 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,083 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,089 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,090 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,090 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,095 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,096 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,096 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,115 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,116 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,116 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,120 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,121 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,122 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,127 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,129 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,129 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,134 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,135 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,136 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,141 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,142 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,143 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,148 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,150 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,150 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,157 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,163 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,163 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,166 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,171 [job_status.py:show_file_thumbnail()] - Bucket_V2.4-350.gcode
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,171 [job_status.py:show_file_thumbnail()] - no pixbuf
May 13 19:25:00 mainsailos KlipperScreen-start.sh[5301]: 2024-05-13 19:25:00,174 [job_status.py:update_file_metadata()] - Cannot find file metadata. Listening for updated metadata
*repeat thousands of times*

**Comment by alfrix** [comment]
the loop seems to get infinite because there is no metadata response ever, the turnaround time of the callback is a bit suspicious.
to avoid this situation i'll patch it up where if there was no metadata make only one request per file. no loop
