### ISSUE TITLE
Updated to Python 3.11 Klipperscreen stopped working

### ISSUE THREAD

**Issue by gfosdike1** [KlipperScreen/KlipperScreen#1383]
### What happened?

I upgraded to Python 3.11 and Klipperscreen now states that the host does not meet minimum requirements. It seems to think I'm using 3.7

### What did you expect to happen instead?

Klipperscreen continued to work

### How to reproduce this bug?

Upgrade to Python 3.11

### Log output

[logs-20240530-093631.zip](https://github.com/KlipperScreen/KlipperScreen/files/15496150/logs-20240530-093631.zip)

**Comment by Robnex** [comment]
What's your solution ?

**Comment by gfosdike1** [comment]
> What's your solution ?

I ended up rebuilding from the ground up, a bit drastic but it save a lot of hassle!
