### ISSUE TITLE
[BUG] Syntax error in KlipperScreen-install.sh: line 154

### ISSUE THREAD

**Issue by NikolayMurha** [KlipperScreen/KlipperScreen#1384]
### What happened?

/home/pi/KlipperScreen/scripts/KlipperScreen-install.sh: line 154: syntax error near unexpected token `}'

### What did you expect to happen instead?

Installation

### How to reproduce this bug?

Try to install using KlipperScreen-install.sh

### Log output

```
/home/pi/KlipperScreen/scripts/KlipperScreen-install.sh: line 154: syntax error near unexpected token `}'
/home/pi/KlipperScreen/scripts/KlipperScreen-install.sh: line 154: `}'

#=======================================================#
 KlipperScreen installation failed!
#=======================================================#
```

**Comment by HaniAlotaibi** [comment]
i just had the same issue exactly. my screen was not working (BTT HDMI5), removed the installed version, and when i tried to reinstall it, it  didnt work, direct install via KlipperScreen-install.sh and via Kiauh

**Comment by dr-pavel** [comment]
I think we need to add the **fi** operator after 
these lines:
```
 if [ -d $KSENV ]; then
        echo_text "Removing old virtual environment"
        rm -rf ${KSENV}
```
You should get something like this:
```
if [ -d $KSENV ]; then
    echo_text "Removing old virtual environment"
    rm -rf ${KSENV}
    fi
```
then run the script:
`KlipperScreen-install.sh`

In my case, the installation was successful.

**Comment by teunvandenburg** [comment]
> I think we need to add the **fi** operator after these lines:
> 
> ```
>  if [ -d $KSENV ]; then
>         echo_text "Removing old virtual environment"
>         rm -rf ${KSENV}
> ```
> 
> You should get something like this:
> 
> ```
> if [ -d $KSENV ]; then
>     echo_text "Removing old virtual environment"
>     rm -rf ${KSENV}
> fi
> ```
> 
> then run the script: `KlipperScreen-install.sh`
> 
> In my case, the installation was successful.

Works for me aswel thanks a lot.

**Comment by Safiro1** [comment]
I having the exact same issue when trying manual installation or using KIAUH.
Please let us know when this is fixed.
Thanks!

**Comment by Safiro1** [comment]
> > I think we need to add the **fi** operator after these lines:
> > ```
> >  if [ -d $KSENV ]; then
> >         echo_text "Removing old virtual environment"
> >         rm -rf ${KSENV}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You should get something like this:
> > ```
> > if [ -d $KSENV ]; then
> >     echo_text "Removing old virtual environment"
> >     rm -rf ${KSENV}
> > fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then run the script: `KlipperScreen-install.sh`
> > In my case, the installation was successful.
> 
> Works for me aswel thanks a lot.

Where did you add those conditionals?

**Comment by Smurfj3** [comment]
Same problem here, fixing the script made the script go, however half way the installation I now get the error "KlipperScreen-install.sh: line 124: /home/android/.KlipperScreen-env/bin/activate: No such file or directory"

**Comment by Smurfj3** [comment]
This breaks the Kiauh installation helper completely because even changing the KlipperScreen-Install.sh does not make a difference because Kiauh will redownload the files from github. Hopefully this gets updated soon :D

**Comment by arraylabs** [comment]
Stuck in Kiauh with this as well

**Comment by Smurfj3** [comment]
> Stuck in Kiauh with this as well

Yeah I got it working but it was a bit of a B

**Comment by brunobold** [comment]
#1385 Pull request submitted with fix.

**Comment by alfrix** [comment]
i was busy and did not have the time to even look at the repo until now, thanks bruno, and sorry to everyone for the inconvenience.
