### ISSUE TITLE
[BUG] Z-Calibrate starts BED_MESH_CALIBRATE

### ISSUE THREAD

**Issue by hapklaar** [KlipperScreen/KlipperScreen#1403]
### What happened?

Wanted to run a Z-Calibrate from Klipperscreen, but hitting Start starts a BED_MESH_CALIBRATE instead. After this all buttons on the Z Calibrate screen became unavailable.

### What did you expect to happen instead?

Expected the head to go to the center and 5 mm above the bed, ready to manually do a Z calibration

### How to reproduce this bug?

Start Z-Calibrate from Klipperscreen menu

### Additional information:

Ratrig 3.0 400 with Beacon eddy current probe

KlipperScreen v0.4.2-11-g629c86d9

### Log output

```
2024-06-13 19:35:57,066 [screen.py:attach_panel()] - Current panel hierarchy: main_menu > more > zcalibrate
2024-06-13 19:36:14,613 [KlippyWebsocket.py:gcode_script()] - Sending printer.gcode.script: SET_GCODE_OFFSET Z=0
2024-06-13 19:36:14,615 [KlippyWebsocket.py:gcode_script()] - Sending printer.gcode.script: BED_MESH_CALIBRATE
2024-06-13 19:36:58,587 [KlippyGtk.py:remove_dialog()] - Cannot remove dialog <Gtk.Dialog object at 0xf0b3ad88 (GtkDialog at 0x220c360)>
2024-06-13 19:36:58,707 [KlippyGtk.py:Dialog()] - Showing dialog KlipperScreen (width=2048, height=1536)

```

**Comment by alfrix** [comment]
not a bug, unsupported probe type, the behavior could be improved, i wanted to throw an easier path to manually calibrate if you did not have a probe, but it will likely be imposible to maintain current behaviour with devs of modules adding custom names to whats essentially just a probe_calibrate

**Comment by hapklaar** [comment]
I do very much like it that when I start a `BEACON_CALIBRATE` from cmdline, the correct manipulation interface shows on KS, but doing a `BED_MESH_CALIBRATE` upon selecting a Z-Calibrate rather unexpected. Maybe we can swap menu items when a Beacon is detected, or make it configurable in config?

**Comment by alfrix** [comment]
> but doing a BED_MESH_CALIBRATE upon selecting a Z-Calibrate rather unexpected

i've added the method that will be used to the button name.

if you want to start it using custom commands do something like:

```
[gcode_macro PROBE_CALIBRATE]
rename_existing: PROBE_CALIBRATE_BASE
gcode:
    BEACON_CALIBRATE
```

i will not be adding custom module commands to mainline, i will probably create some sort of custom config at a later point
