### ISSUE TITLE
Cannot install KlipperScreen 

### ISSUE THREAD

**Issue by jallen810** [KlipperScreen/KlipperScreen#1406]
### What happened?

Was using older build of K.S. and tried to update but it said I needed newer version of Python 3.8+
I installed Python 3.8 but then the install scripts failed. 
I installed Python 3.12.4 and now Kiauh & Mainsail say it is fully installed but i still get the errors in screenshots and Klipper Screen does NOT actually run.
![Screenshot 2024-06-19 085832](https://github.com/KlipperScreen/KlipperScreen/assets/62486440/417c4486-14d0-43c1-bdc1-3390d65e4626)
![Screenshot 2024-06-19 085900](https://github.com/KlipperScreen/KlipperScreen/assets/62486440/e7c78d51-f4f3-4d80-bf3f-4f12f9eba274)

### What did you expect to happen instead?

Install properly

### How to reproduce this bug?

Tried first using only minimal version of Python3.8 required. Then updated to 3.12.4 and same issue

### Log output

See screen shots.

**Comment by alfrix** [comment]
Not a bug, cannot build dependencies they depend on the host system, usually you dont "update python" that will not go well as dependencies expect to have newer libraries, you need to update the OS
