### ISSUE TITLE
I am unable to install KlipperScreen

### ISSUE THREAD

**Issue by DJKyomi** [KlipperScreen/KlipperScreen#1413]
[bash.txt](https://github.com/user-attachments/files/15974142/bash.txt)
### What happened?

The installation of Klipperscreen always fails with this error
[Klipperscreen_error.txt](https://github.com/user-attachments/files/15973879/Klipperscreen_error.txt)

### What did you expect to happen instead?

i can to nothing 

### How to reproduce this bug?

?

### Additional information:

Orange PI PC + , Armbian latest Release 

### Log output

[logs-20240625-174111.zip](https://github.com/user-attachments/files/15973903/logs-20240625-174111.zip)

**Comment by alfrix** [comment]
you may need to install libsystemd 

apt install libsystemd0

**Comment by DJKyomi** [comment]
is the latest version 
sudo apt install systemd 
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
systemd ist schon die neueste Version (249.11-0ubuntu3.12).
systemd wurde als manuell installiert festgelegt.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.

sudo apt install libsystemd0
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
libsystemd0 ist schon die neueste Version (249.11-0ubuntu3.12).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.

**Comment by alfrix** [comment]
in their docs says it's not required since 0.8
try also installing the headers
apt install libsystemd-dev

**Comment by DJKyomi** [comment]
So the error is only under Armbian Ubuntu Jammy, I have now deleted the entire Orangepi and installed Armbian 
Debian Bookworm and it works wonderfully

**Comment by alfrix** [comment]
close with [cee185e](https://github.com/KlipperScreen/KlipperScreen/commit/cee185e21e6cf7fc2039d3ace8591a8b81ff1ae7)
