### ISSUE TITLE
[BUG] <title>Clicking on the network button shows that there is no sdbus_block module

### ISSUE THREAD

**Issue by sybf** [KlipperScreen/KlipperScreen#1428]
### What happened?

Clicking on the network button shows that there is no sdbus_block module

### What did you expect to happen instead?

Displays network management

### How to reproduce this bug?

I don't know how it came to be
![Uploading image.png…]()

### Additional information:

![aae5c5c66b68e254e2673ad91e9a993](https://github.com/KlipperScreen/KlipperScreen/assets/111949644/da42e675-4d6d-46b8-8b76-0d7e207e65d0)
![f9e0d50e3071f91c51202fa2e407ac1](https://github.com/KlipperScreen/KlipperScreen/assets/111949644/410187af-cdca-42d4-b626-bbb78cf033fe)

### Log output

[KlipperScreen.log](https://github.com/user-attachments/files/16135713/KlipperScreen.log)

**Comment by OnAdditive** [comment]
I'm also having this same bug, updated to KlipperScreen v0.4.3-23-gf9392e67 and suddenly can't access the network menu

**Comment by sybf** [comment]
The problem has been solved, uninstall and reinstall it

> 我也有同样的错误，更新到 KlipperScreen v0.4.3-23-gf9392e67，突然无法访问网络菜单

**Comment by sybf** [comment]
The problem has been solved, uninstall and reinstall it

**Comment by Khaos66** [comment]
@sybf When will you push a new release?
I use Yumi PAD and it checks for new releases to update KlipperScreen

**Comment by sybf** [comment]
If the network panel cannot be displayed after updating the klipperscreen, please replace the network environment and uninstall and reinstall the klipperscreen


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KlipperScreen/KlipperScreen"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月13日(星期二) 晚上11:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KlipperScreen/KlipperScreen] [BUG] <title&gt;Clicking on the network button shows that there is no sdbus_block module (Issue #1428)





 
@sybf When will you push a new release?
 I use Yumi PAD and it checks for new releases to update KlipperScreen
