### ISSUE TITLE
temperature too low to extrude

### ISSUE THREAD

**Issue by tome9111991** [KlipperScreen/KlipperScreen#1434]
### Requested feature

After one of the latest updates, I get the message "temperature too low to extrude." 
This is quite annoying when I want to execute my load or unload macro. I have written my macros in such a way that the temperatures are set within the macro itself, but unfortunately, this no longer works after the update. 
The macro aborts, and I get the message "temperature too low to extrude." 

Is there a way to deactivate this feature?

**Comment by tyllurius** [comment]
Exakt same here. Some new extruder temperature check cause my load/unload macros not to work anymore for same reasons. Same macros started from UI still work as expected.

**Comment by Robnex** [comment]
Same here

**Comment by yzheka** [comment]
Same. Please revert as it was before.
