### ISSUE TITLE
[BUG] Layer X out of Y

### ISSUE THREAD

**Issue by roykrikke** [KlipperScreen/KlipperScreen#1439]
### What happened?

In Fluidd I can see Layer X out of Y
![image](https://github.com/user-attachments/assets/3f4198d9-badd-4aba-a172-4ad5c26d0e19)

In KlipperScreen I can't see this anymore

### What did you expect to happen instead?

Layer X out of Y

### How to reproduce this bug?

Open de screen where Layer X out of Y is normally shown. 

### Additional information:

KlipperScreen: v0.4.3-40

### Log output

[logging.txt](https://github.com/user-attachments/files/16324625/logging.txt)

**Comment by alfrix** [comment]
not a bug, klipperscreen will not calculate and guess the layer anymore, provide the correct info:

https://klipperscreen.github.io/KlipperScreen/Quicktips/#accurate-layer-progress-in-the-secondary-screen-of-the-printing-panel

related: https://github.com/KlipperScreen/KlipperScreen/commit/b58471c5057590c5977594882dba2045a173933b

**Comment by roykrikke** [comment]
> not a bug, klipperscreen will not calculate and guess the layer anymore, provide the correct info:
> 
> https://klipperscreen.github.io/KlipperScreen/Quicktips/#accurate-layer-progress-in-the-secondary-screen-of-the-printing-panel
> 
> related: [b58471c](https://github.com/KlipperScreen/KlipperScreen/commit/b58471c5057590c5977594882dba2045a173933b)

Thanks for the quick response!
