### ISSUE TITLE
[FR] Add Turn on Printer to the main screen instead of connection error if there is a configured power switch

### ISSUE THREAD

**Issue by Online122228** [KlipperScreen/KlipperScreen#1465]
### Requested feature

instead of showing a warning that the mcu cannot be found, show a switch to turn the printer on

### Is your feature request related to a problem?

you always have to select settings then on and then you can turn on the printer, so three clicks what could be one

### Describe alternatives you have considered

1. turning the printer on over Mainsail
2. turning the printer on over the Wi-Fi plug i use
3. turning the printer on with three clicks instead of one
4. leaving the printer always on
5. leaving the printer always off and never use it anymore

**Comment by stijnb1234** [comment]
+1, would be a great feature. Like Mainsail does, show that it's turned off and add a button to switch it on again.

**Comment by mjfsch** [comment]
See here https://github.com/KlipperScreen/KlipperScreen/issues/1241#issuecomment-1900205587

**Comment by Online122228** [comment]
when i inserted this line into my klipperscreen.conf i got an error, i think it was something like a newline error even if i exactly copy pasted it. i add my moonraker.conf for reference
[moonraker.conf.txt](https://github.com/user-attachments/files/17034987/moonraker.conf.txt)

**Comment by mjfsch** [comment]
my klipperscreen.conf reads:

[printer printer]
power_devices: printer
#~# --- Do not edit below this line. This section is auto generated --- #~#

**Comment by Online122228** [comment]
So it is split in two lines?
