### ISSUE TITLE
[BUG] KlipperScreen doesn't have fallback to access the printer host terminal on system failure

### ISSUE THREAD

**Issue by HakunMatat4** [KlipperScreen/KlipperScreen#1499]
### What happened?

My printer is connected to a thin client aka miniPC, and the whole management is done via wireless with the printer located where there is no RJ45 connection, the wireless network details are set on the Linux level.

There was a network change and the printer as expected lost access to the network, and without access to a wired network, it was pure chaos with the heavy printer to move to a place with wired network to fix its wireless config file.

Debian: /etc/network/interfaces

```
auto wlp3s0 
iface wlp3s0 inet dhcp
	wpa-ssid SSID
	wpa-psk  PASSWORD
```

### What did you expect to happen instead?

KlipperScreen should allow you to:

A) Access the host terminal, OR
B) Allow itself to be terminated from its menu which allows you to jump to the virtual terminal, OR
C) Before it auto-start, if a key is pressed due to a keyboard connected, skip it and return the Linux terminal

After that you can restart the host and everything will be back online.

### How to reproduce this bug?

1. Have a printer setup and working via wireless only
2. Change the network details after everything is working
3. KlipperScreen won't grant access to the host terminal

This is a bug, not a feature request!
The printer becomes completely useless with this problem because of KlipperScreen since you cannot:

1. Send files to be printer
2. Without network it cannot updated the klipper, etc.
3. Because KlipperScreen automatically starts, you are locked to it and a broken printer.

### Additional information:

- Dell miniPC
- Wireless network
- Debian Linux

### Log output

[logs-20241105-190851.zip](https://github.com/user-attachments/files/17629254/logs-20241105-190851.zip)

**Comment by alfrix** [comment]
To access the terminal press control+alt+function keys to switch to another virtual terminal (VT), This is a feature of all the distros that i know, in fact it would be rare not to have VT switching unless it's a public kiosk.

for example: CTRL+ALT+F3

one of the VTs (7 probably) will be KlipperScreen so you can switch back and forth.
