### ISSUE TITLE
[BUG] <title>White screen after wake up

### ISSUE THREAD

**Issue by 3D-Cat** [KlipperScreen/KlipperScreen#1505]
### What happened?

after the screen turns black and I'm trying to wake up the screen, I see only a white display. Even though you can't see anything the KlipperScreen reacts on touch. I've this issue with the last KlipperScreen update (v0.4.5-10-g43ad9fc6)

### What did you expect to happen instead?

readable screen after wake up

### How to reproduce this bug?

waking up after the screen is blacked out

### Log output

[KlipperScreen.zip](https://github.com/user-attachments/files/17774215/KlipperScreen.zip)

**Comment by 3D-Cat** [comment]
any idea why this happens? I've no issue when I turn off the screen saver. thanks

**Comment by alfrix** [comment]
> it was working without any issues for more then 1 year, anyway I'll disable dpms. thanks

interesting, if it's really klipperscreen, you can try to revert to a previous version from ssh and test

for example something like this:

```
cd ~/klipperscreen
git reset --hard v0.4.0
sudo service KlipperScreen restart
```

some screens fake dpms making the screen black (GPIO screens for example), if the screen doesn't turn off it's pointless to continue trying to solve it

**Comment by 3D-Cat** [comment]
after disabling DPMS screen turns black after defined time and wake up causes no issues.
I'm not sure if DPMS was enabled or not before update but for me it's OK how it's works now. 
many thanks for your help and grate work

**Comment by 3D-Cat** [comment]
btw I'm using BTT Pad 7 with CM4
