### ISSUE TITLE
[FR] dangerklipper z_tilt_ng support

### ISSUE THREAD

**Issue by kaifas1st** [KlipperScreen/KlipperScreen#1512]
### Requested feature

Would be lovely to add z_tilt_ng detection too so z tilt shows up in homing

**Comment by alfrix** [comment]
there is no support for forks, BUT in this case since the command is the same i will change the condition check for the Z_TILT_ADJUST command instead of the config section and it should work for both and be more correct at the same time.

**Comment by kaifas1st** [comment]
Thank you very much
