### ISSUE TITLE
Console information overlaid on other interfaces. 

### ISSUE THREAD

**Issue by zhengyangliu** [KlipperScreen/KlipperScreen#559]
It seems that the screen stops refreshing after opening the console, resulting in more and more pixels. 

![IMG_20220325_230643](https://user-images.githubusercontent.com/10896145/160147861-4340188a-e23d-41c2-aa82-ca7ee2119954.jpg)

**Comment by alfrix** [comment]
i have never seen that happening, do you have any steps to reproduce the issue?

**Comment by zhengyangliu** [comment]
I am also very confused about this issue, I fetched the latest code and installed, witch theme or change language but nothing helped. This issue sill exist. I don't have any special reproduce steps. Just install KlipperScreen and open the console panel and that's it, but other panels works fine. Heck.

**Comment by zhengyangliu** [comment]
It looks like it's just the console area that's wrong
![IMG_20220327_135315](https://user-images.githubusercontent.com/10896145/160268698-08b5a0f5-941f-47df-8b24-bf2d9b9eb604.jpg)

**Comment by zhengyangliu** [comment]
https://user-images.githubusercontent.com/10896145/160268816-3033d368-faae-4418-b82a-0afba5b4ac2e.mp4

**Comment by skyaee** [comment]
I updated to the latest version and also have the same problem, unable to view the controller content.

**Comment by breakheart** [comment]
same problem

**Comment by Sofronio** [comment]
same here

**Comment by arbaleast** [comment]
I also encountered this problem, is there any solution?

**Comment by alfrix** [comment]
never provided log, couldn't reproduce

**Comment by zhengyangliu** [comment]
I can no longer reproduce this problem in the new version, it has been fixed.
