### ISSUE TITLE
Zbolt theme - it is hard to see the selections on the fine tuning pages

### ISSUE THREAD

**Issue by simpat1zq** [KlipperScreen/KlipperScreen#594]
I have 2 different types of screens. One is the official pieces display and the other 2 are hdmi/usb. When I'm on the fine tuning page while using the zbolt theme, it is very difficult to see the which adjustment is selected at the bottom. On the Pi display, I can only tell if I'm looking directly in front if the display. If I'm at a slight angle, the color looks the same as the unselected values. 

On the hdmi displays, I can barely tell the difference, no matter the angle. I think it might be better to use a different color for the selected value. Or is there a way to make the change myself? I couldn't find the docs on the themes.

**Comment by alfrix** [comment]
your hardware has bad viewing angles, use another theme or copy it with another name and modify it, i will not change it, since the theme is maintained by Jordan and i leave the the decision to him

**Comment by beroliv** [comment]
i have the same issue with all the themes, very difficult to see wich button is active.
i
