### ISSUE TITLE
[FR] Multiple/idle extruder icons present

### ISSUE THREAD

**Issue by XOIIO** [KlipperScreen/KlipperScreen#668]
I think it would be a good addition to show the icons in the top left for multiple extruders and idle extruders at all time, as with a dual extrusion machine, only having one is less than ideal, and it does not switch over to show the temperature of the second extruder when manually setting it to exchange filaments. 

I believe it should be a pretty quick thing to implement and could even have a menu option to select which extruders are present, for instance if someone has a toolchanger with several and did not want so many.

**Comment by alfrix** [comment]
98da293ceeeb63b374c67e8518ecbaabbb21fcbd
