### ISSUE TITLE
[BUG] Installer Should look for /dev/tty permissions

### ISSUE THREAD

**Issue by csiess85** [KlipperScreen/KlipperScreen#946]
**Describe the bug**
Running KlipperScreen fails on Raspberry Pi Lite due to /dev/tty* having 0620 permission.

**To Reproduce**

Install plain Raspberry Pi Lite and KlipperScreen via kiauh

**Expected behavior**
KlipperScreen starts

**FIX**

I created /etc/udev/rules.d/99_persistent-local.rules with:
SUBSYSTEM=="tty", KERNEL=="tty[0-9]*", GROUP="tty", MODE="0660"

**Comment by alfrix** [comment]
oops typo!, also this should work if the user is on the tty group, the installer does it 


usermod -a -G tty pi

**Comment by alfrix** [comment]
/dev/tty0-9 are 620 by default and KS works as expected on my system
