### ISSUE TITLE
[FR] LED

### ISSUE THREAD

**Issue by Vasilyev81** [KlipperScreen/KlipperScreen#991]
Hi, I'm Andrey.
From the beginning, I want you to know that I have no experience in contributing to an open source, so if I do something in an unusual/inappropriate way, do not hesitate to let me know about it, and please be patient.
In short, I have almost finished the development of the led panel, and just now I thought that (maybe) it is not implemented yet for some specific reasons.
The question is:  would you like to consider accepting a PR that implements led management functionality?
Below is a filled-out FR template from GitHub
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to control the LED light from the KlipperScreen.

**Describe the solution you'd like**
I'm at the end of development and hope to finish it in the next few days. 

**Describe alternatives you've considered**
Currently, I have decided to go with scale for each color in rgb/rgbw mix; in the beginning, I considered using a color chooser widget, but I didn't find a way to customize it to RGBW color mix.

**Additional context**
Currently, as an environment, I have a Raspberry with a connected mouse and external screen and the second environment is  on Ender 3 V2 + Bigtreetech Manta E3EZ mainboard + Bigtreetech CB1 + sensor screen + neopixel led light.

**Comment by Vasilyev81** [comment]
Here's how it looks right now, the LED panel is accessible from the actions menu![PXL_20230526_211027697.jpg](https://github.com/jordanruthe/KlipperScreen/assets/26001746/c20dd220-ead9-45c8-bcfb-28d7c0bc4be1)

![PXL_20230526_210901327.jpg](https://github.com/jordanruthe/KlipperScreen/assets/26001746/de28e2c9-c914-4971-8f26-f29ee5316486)

![PXL_20230526_210826766.jpg](https://github.com/jordanruthe/KlipperScreen/assets/26001746/1e68fc3f-a787-493b-91c6-744b369c936c)

![PXL_20230526_210848106.jpg](https://github.com/jordanruthe/KlipperScreen/assets/26001746/d113bf46-5e26-475b-b4eb-535de8ca95c1)

**Comment by alfrix** [comment]
hi, thank you for helping

>  What do you think about the UI layout? Is it okay?

a color-picker would be preferred, there are some ways to convert to rgbw search online

> Is it necessary to implement management of more than one RGB/RGBW led device?

Yes, but starting with one is ok.

> How common is it to have more than one RGB/RGBW led device?

idk we don't have statistics that i know

**Comment by Vasilyev81** [comment]
Okay, I get it. Will look for rgbw color picker.
Thanks!

**Comment by Vasilyev81** [comment]
Hi, I'm kind of stuck
When I'm adding ColorChooserWidget in this way:
`self.color_chooser = Gtk.ColorChooserWidget()
  self.color_chooser.set_vexpand(True)
  self.color_chooser.set_hexpand(True)
  self.color_chooser.set_valign(Gtk.Align.FILL)
  self.color_chooser.set_halign(Gtk.Align.FILL)
  self.content.pack_start(self.color_chooser, True, True, 0)`

it is not fill all available space in the self.content
What I'm doing wrong? Any advice/help appreciated

**Comment by alfrix** [comment]
i have come across that issue, try placing it inside a grid it usually solves it

**Comment by jay1st** [comment]
the FLSUN pad has 2 LED buttons, can we have that added or a HOWTO ?

**Comment by Vasilyev81** [comment]
Hi! Did you mean Flsun Speeder Pad

**Comment by jay1st** [comment]
> Hi! Did you mean Flsun Speeder Pad

Oh yes exactly

**Comment by floodo1** [comment]
> Okay, I get it. Will look for rgbw color picker. Thanks!

Fluidd uses this color picker. I find the circle (hue/saturation) and slider (brightness) works well. Would love to see something similar in Klipperscreen!

![image](https://github.com/KlipperScreen/KlipperScreen/assets/12222886/3c2898b0-02f1-480e-853c-d8978e4fa355)

**Comment by Vasilyev81** [comment]
> So I revise my statement: "Would love to see _any led interface_ in Klipperscreen!"

Soon)
